# Generated by Django 4.0.5 on 2023-09-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_remove_todo_task_todo_assignees_todo_assigner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='comentariofinal',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
