# Generated by Django 4.0.5 on 2023-09-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_todo_pausado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pausado',
            field=models.BooleanField(blank=True),
        ),
    ]
