# Generated by Django 4.0.5 on 2023-10-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_alter_todo_pausado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assignees',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
