# Generated by Django 4.0.5 on 2023-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adm', 'Administrador'), ('gm', 'GM'), ('tec', 'Técnico')], default='tec', max_length=3),
        ),
    ]
