# Generated by Django 4.0.5 on 2023-10-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authusers', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='matricula',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
